- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart networking
  service:
    name: networking
    state: restarted

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: restart network (centos)
  service:
    name: network
    state: restarted

